---
title: Reporting and displaying your results using papaja
shorttitle: 
author: Marius Barth
affiliation: University of Cologne

abstract: 

note: Currently, a development version of `papaja` is available at https://github.com/crsh/papaja.

keywords: 

class: man
lang: american
figsintext: yes
lineno: yes
bibliography: references.bib

output: papaja::apa6_pdf
---
```{r message = FALSE, warning = FALSE}
library(papaja)
library(dplyr)

apa_prepare_doc() # Prepare document for rendering

# set some defaults
knitr::opts_chunk$set(cache=FALSE, echo=FALSE, warning=FALSE, message=FALSE, fig.width=8.8, fig.height=4.4)

# load data
load("./data/exp1.RData")
```

# Results

```{r}
# first calculate the proportion of correct responses
tmp <- aggregate(correct~material+generation+order+instruction+id,data=pd.data,FUN=mean,na.rm=TRUE)

# visualize your data
apa_barplot(data=tmp,id="id",factors=c("material","instruction"),dv="correct",fun.aggregate=mean,tendency=mean,,dispersion=,level=.98,ylim=c(0,1))


```

For each participant, we calculated the proportion of correctly generated *second order conditionals*. We then conducted a



# References
