name: No Response

on:
  issue_comment:
    types: [created]
  schedule:
    # Schedule 18:00 once every day
    - cron: '0 18 * * *'

jobs:
  noResponse:
    runs-on: ubuntu-latest
    steps:
      - uses: lee-dohm/no-response@v0.5.0
        with:
          token: ${{ github.token }}
          daysUntilClose: 28
